name: safepass
description: "Offline Password Storage and Generator"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.8

  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

  flutter_secure_storage: ^9.2.2
  encrypt: ^5.0.3

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

